version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: aml-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Slayer!9"
    ports:
      - "1433:1433"
    volumes:
      - amldb:/var/opt/mssql


  aml-service-img:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aml-service
    depends_on:
      - db
    ports:
      - "5193:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MyDb=Server=db;Database=AMLServiceDB;User Id=sa;Password=Slayer!9;TrustServerCertificate=true;
      - RabbitMQ__host_name=76.13.15.132
      - RabbitMQ__port=5672
      - RabbitMQ__user_name=guest
      - RabbitMQ__password=guest

volumes:
  amldb:
